# Generated by Django 3.1.1 on 2020-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phoneNumber',
            field=models.IntegerField(blank=True, default=None, verbose_name='Phone'),
        ),
    ]
