# Generated by Django 3.1.1 on 2020-09-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phoneNumber',
        ),
    ]
