# Generated by Django 3.1.1 on 2020-09-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
