# Generated by Django 3.1.1 on 2020-09-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200924_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='token',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('emailAddress', models.EmailField(blank=True, max_length=250, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='address')),
                ('phoneNumber', models.IntegerField(blank=True, verbose_name='phone')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ('customerName',),
            },
        ),
    ]
